# Dockerfile
FROM node:22-alpine AS base

WORKDIR /app

# Install Yarn
RUN apk add --no-cache yarn

# Copy package.json and yarn.lock (if available)
COPY package.json yarn.lock* ./

# Install dependencies
RUN yarn install --frozen-lockfile

COPY . .

EXPOSE 3000

CMD ["yarn", "dev"]