# Build stage
FROM node:22-alpine AS build

WORKDIR /src
COPY package.json yarn.lock* ./
RUN yarn install
COPY . .

RUN yarn build

# Production stage
FROM build AS production

COPY --from=build /src/.next ./.next
COPY --from=build /src/node_modules ./node_modules
COPY --from=build /src/package.json ./package.json
COPY --from=build /src/public ./public

CMD yarn start
